version: "3.8"

services:
  database:
    image: postgres:latest
    container_name: nexa-database
    environment:
      POSTGRES_DB: nexa_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql
    networks:
      - nexa-network

  message-broker:
    image: 'rabbitmq:management'
    container_name: 'nexa-message-broker'
    environment:
      - 'RABBITMQ_DEFAULT_PASS=admin'
      - 'RABBITMQ_DEFAULT_USER=admin'
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - nexa-network

volumes:
  db_data:
  rabbitmq_data:


networks:
  nexa-network:
    driver: bridge
