spring.datasource:
    url: jdbc:postgresql://localhost:5432/nexa_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

spring.rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin