spring:
  application:
    name: nexa
    version: SNAPSHOT-1.0.0

server:
  servlet:
    context-path: /api

spring.datasource:
    url: jdbc:postgresql://localhost:5432/nexa_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

springdoc:
    api-docs:
      path: /docs
    swagger-ui:
      path: /swagger-ui.html

spring.rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin